<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="base_length" value="0.1"/>
    <xacro:property name="base_width" value="0.1"/>
    <xacro:property name="base_height" value="0.02"/>
    <xacro:property name="forearm_length" value="0.3"/>
    <xacro:property name="forearm_radius" value="0.02"/>
    <xacro:property name="hand_length" value="0.3"/>
    <xacro:property name="hand_radius" value="0.02"/>

    <!-- <link name="base_footprint">
        
    </link> -->

    <link name="arm_base_link">
        <visual>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}"/>
            </geometry>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/> 
            <material name="orange"/>           
        </visual> 
        
        <xacro:box_inertia m="0.5" l="${2*base_length}" w="${2*base_width}" h="${2*base_height}" xyz="0 0 0" rpy="0 0 0"/> 
        
        <collision>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}"/>
            </geometry>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/> 
        </collision>
    </link>

    <!-- <joint name="base_arm_joint" type="fixed">
        <parent link="base_footprint"/>
        <child link="arm_base_link"/>
        <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
    </joint> -->

    <link name="forearm_link">
        <visual>
            <geometry>
                <cylinder radius="${forearm_radius}" length="${forearm_length}"/>
            </geometry>
            <origin xyz="0.0 0.0 ${forearm_length/2.0}" rpy="0.0 0.0 0.0"/>
            <material name="yellow"/>
        </visual>

        <xacro:cylinder_inertia m="0.5" r="${2*forearm_radius}" l="${2*forearm_length}" xyz="0 0 0" rpy="0 0 0"/> 

        <collision>
            <geometry>
                <cylinder radius="${forearm_radius}" length="${forearm_length}"/>
            </geometry>
            <origin xyz="0.0 0.0 ${forearm_length/2.0}" rpy="0.0 0.0 0.0"/>            
        </collision>
    </link>

    <joint name="base_forearm_joint" type="revolute">
        <parent link="arm_base_link"/>
        <child link="forearm_link"/>
        <axis xyz="0.0 1.0 0.0"/>
        <limit lower="0.0" upper="${pi/2.0}" effort="100.0" velocity="100.0"/>
        <dynamics damping="0.05" friction="0.1"/>
        <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
    </joint>

    <link name="hand_link">
        <visual>
            <origin xyz="0.0 0.0 ${hand_length/2}" rpy="0.0 0.0 0.0"/>
            <geometry>
                <cylinder radius="${hand_radius}" length="${hand_length}"/>
            </geometry>
            <material name="orange"/>
        </visual>
        
        <xacro:cylinder_inertia m="0.5" r="${3*hand_radius}" l="${3*hand_length}" xyz="0 0 0" rpy="0 0 0"/> 

        <collision>
            <origin xyz="0.0 0.0 ${hand_length/2}" rpy="0.0 0.0 0.0"/>
            <geometry>
                <cylinder radius="${hand_radius}" length="${hand_length}"/>
            </geometry>            
        </collision>
    </link>

    <joint name="forearm_hand_joint" type="revolute">
        <parent link="forearm_link"/>
        <child link="hand_link"/>
        <axis xyz="0.0 1.0 0.0"/>
        <limit lower="0.0" upper="${pi/2.0}" effort="100.0" velocity="100.0"/>
        <dynamics damping="0.05" friction="0.1"/>
        <origin xyz="0.0 0.0 ${forearm_length}" rpy="0.0 0.0 0.0"/>
    </joint>

</robot>