<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="lidar_length" value="0.1"/>
    <xacro:property name="lidar_width" value="0.1"/>
    <xacro:property name="lidar_height" value="0.1"/>

    <link name="lidar_link">
        <visual>
            <geometry>
                <box size="${lidar_length} ${lidar_width} ${lidar_height}"/>
            </geometry>
            <material name="grey"/>
        </visual>
        <collision>
            <geometry>
                <box size="0.1 0.1 0.1"/>
            </geometry>
            <xacro:box_inertia m="2" l = "2" w="5" h="5" xyz="0 0 0" rpy="0 0 0"/>
        </collision>
    </link>

    <joint name="base_lidar_joint" type="fixed">
        <parent link="base_link"/>
        <child link="lidar_link"/>
        <origin xyz="0.0 0.0 ${base_height + (lidar_height/2.0)}" rpy="0.0 0.0 0.0"/>
    </joint>
</robot>